Repository appy-one/acebase-server, pull requests merged in 2022-11, with the labels that each got.

#42 Bump acebase v1.26.0, acebase-core v1.24.0
  dist/cjs/routes/data-reflect.js
  dist/cjs/routes/data-reflect.js.map
  dist/esm/routes/data-reflect.js
  dist/esm/routes/data-reflect.js.map
  package-lock.json
  package.json
  src/routes/data-reflect.ts
Labels: dependencies

#43 bump acebase to v1.26.1
  package-lock.json
  package.json
Labels: dependencies

#47 Disable import of ESM modules until stable
  package-lock.json
  package.json
Labels: bug

#54 Add missing server options
  src/server.ts
  src/settings/index.ts
Labels: enhancement
